### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by MrBrN197** [MrBrN197/MusicBoard#21]
### Github Project Link
https://github.com/MrBrN197/Capstone-2-Project

We are 2 people working on this project.

**Comment by Georjane** [comment]
### Hello, Team <STUDENTS>, ✋🏽 

Great job making a copy and setting up your Kanban board.
However, we have a few more changes to make in order to meet all requirements for this step to be approved but you are almost there!

## Required Changes ♻️

- [ ] All cards with `Student C` suffix on the template should be removed since there are just 2 students in the team.
- [ ] All cards with `group task` in the title should be assigned to someone (it does not matter to whom as you guys have the freedom to choose).

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by MrBrN197** [comment]
@Georjane Thank you, We've implemented the necessary changes

**Comment by EricMbouwe** [comment]
### Hi team, 

# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
